spring.application.name=autoflex

# dataBase configs
spring.datasource.url=${DB_URL:jdbc:postgresql://127.0.0.1:6543/autoflex}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:[YOUR_BANK_PASSWORD]}
spring.datasource.initialization-mode=always
spring.datasource.data=classpath:data.sql

# JPA/Hibernate configs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
 
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# tomcat default port
server.port: 5000

# configs Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

logging.level.root=ERROR
logging.level.org.springframework=ERROR 